# Generated by Django 2.0.2 on 2018-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180227_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cdna',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='genomic',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='protein',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
