# Generated by Django 2.0.2 on 2018-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180228_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='cdna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='genomic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='protein',
            field=models.CharField(max_length=100),
        ),
    ]
