# Generated by Django 2.0.2 on 2018-03-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180228_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Description'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Platform'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Stage'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Variant'),
        ),
    ]
