# Generated by Django 2.0.2 on 2018-03-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20180301_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id_platform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id_variant',
            new_name='variant',
        ),
    ]
