# Generated by Django 2.0.2 on 2018-03-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_stage_stage_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_str',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
