# Generated by Django 2.0.2 on 2018-03-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20180301_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id_annotation', models.AutoField(primary_key=True, serialize=False)),
                ('rsid', models.CharField(max_length=100)),
                ('polyphen', models.CharField(max_length=100)),
                ('sift', models.CharField(max_length=100)),
                ('gnomad_af', models.CharField(max_length=100)),
                ('id_variant', models.ForeignKey(db_column='id_variant', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Variant')),
            ],
            options={
                'db_table': 'annotation',
            },
        ),
    ]
