# Generated by Django 2.0.2 on 2018-03-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='id_variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='gnomad_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='polyphen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='rsid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='sift',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
